name: ShellCheck

on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master, development ]

permissions:
  contents: read

jobs:
  shellcheck:
    name: Lint ash scripts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run ShellCheck
        run: shellcheck firewall.sh
